[workspace]
members = [
    "actix-amqp",
    "actix-amqp/codec",
    "actix-cors",
    "actix-identity",
    "actix-mqtt",
    "actix-mqtt/codec",
    "actix-protobuf",
    "actix-protobuf/examples/prost-example",
    "actix-redis",
    "actix-session",
    "actix-web-httpauth",
]

[patch.crates-io]
actix-session = { path = "actix-session" }
mqtt-codec = { path = "actix-mqtt/codec" }
amqp-codec = { path = "actix-amqp/codec" }
